/* Generated by the NeXT Project Builder 
   NOTE: Do NOT change this file -- Project Builder maintains it.
*/

#import <appkit/Application.h>

void main(int argc, char *argv[]) {

    [Application new];
    if ([NSApp loadNibSection:"DoomEd.nib" owner:NXApp withNames:NO])
	    [NSApp run];
	    
    [NSApp free];
    exit(0);
}
